[package]
name = "tidk"
version = "0.2.0"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2021"

[dependencies]
bio = "0.41.0"
rust-htslib = { version = "*", default-features = false }
clap = { version = "3.1.8", features = ["cargo"] }
rayon = "1.5.0"
# in explore::get_telomeric_repeat_estimates()
itertools = "0.10.0"
cmd_lib = "1.0.10"
# in utils::lms()
lexical-sort = "0.3.1"
# for plotting
csv = "1.1.5"
serde = "1.0.123"
# clade table
tabled = "0.6.0"
chrono = "0.4.19"